### ISSUE TITLE
aprod callback memory issue

### ISSUE THREAD

**Issue by jakevdp** [jakevdp/pypropack#1]
On my 32bit linux box, the callback function overwrites some memory which causes a failure in the matrix dot product.  Spent a while trying to track it down... I currently have no idea what's causing the problem.

This is the code that reproduces it:

``` python
import numpy as np
from pypropack import svdp
from scipy.sparse import csr_matrix

np.random.seed(0)
A = np.random.random((10, 20))
u, sigma, v = svdp(csr_matrix(A), 3)
```

This is fine on my 64-bit linux box, but on the 32-bit box results in:

```
capi_return is NULL
Call-back cb_daprod_in___user__routines failed.
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    u, sigma, v = svdp(csr_matrix(A), 3)
  File "/home/vanderplas/Opensource/pypropack/pypropack/propack.py", line 161, in svdp
    work, iwork, doption, ioption, dparm, iparm)
  File "/home/vanderplas/Opensource/pypropack/pypropack/propack.py", line 46, in __call__
    y[:] = self.A.rmatvec(x)
  File "/home/vanderplas/VIRTUALENV/pydev/local/lib/python2.7/site-packages/scipy/sparse/linalg/interface.py", line 216, in rmatvec
    return self.A_conj.dot(x)
  File "/home/vanderplas/VIRTUALENV/pydev/local/lib/python2.7/site-packages/scipy/sparse/base.py", line 211, in dot
    return self * other
  File "/home/vanderplas/VIRTUALENV/pydev/local/lib/python2.7/site-packages/scipy/sparse/base.py", line 243, in __mul__
    return self._mul_vector(other)
  File "/home/vanderplas/VIRTUALENV/pydev/local/lib/python2.7/site-packages/scipy/sparse/compressed.py", line 261, in _mul_vector
    other.dtype.char))
ValueError: On entry to DLASCL parameter number 4 had an illegal value
```

if `print x` is added to `_Aprod.__call__` in `pypropack/propack.py`, the error does not occur.  This makes me think it's some sort of memory error in the callback function.

**Comment by philip-semanchuk** [comment]
We see the same problem from time to time in our version of the same code. Our ticket is here:
https://scion.duhs.duke.edu/vespa/hlsvdpro/ticket/2
